dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
script:
  - "python mattermost.py --url https://example.com --notificationtype CUSTOM --hostalias myexample.com"
