- hosts: icinga
  name: Run icinga master
  tasks:
    - name: ensure icinga2 is installed
      package:
        name: icinga2
        state: present
    - name: Copy icinga config
      copy:
        src: files/conf.d
        dest: /etc/icinga2/
    - name: Copy mattermost Plugin
      copy:
        src: files/icinga2-mattermost
        dest: /usr/lib/nagios/plugins/
    - name: Change file ownership, group and permissions
      file:
        path: /usr/lib/nagios/plugins/icinga2-mattermost/mattermost.py
        owner: root
        group: root
        mode: '0755'

